// Detect the first meaningful record, ignoring the PBN's optional % header/comments.
// A BBO Helper export starts with "% Generated by ..." before [Event ...].
export function detectFormat(text) {
  const content = text.replace(/^\uFEFF/, "");
  const first = content.split(/\r?\n/).find(line => {
    const s = line.trim();
    return s && !s.startsWith("%");
  })?.trim() || "";
  if (/^\[[A-Za-z][A-Za-z0-9_]*\s+"/.test(first)) return "pbn";
  if (/(?:^|\|)md\|/i.test(content)) return "lin";
  return null;
}
